name: Screenshot generation
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    #- run: npm test
    - run: node index.js
    - run: ls
    - run: ls output/
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: /output/
